CREATE TABLE dbo.llm_competitor_price_comparison(
    id INT IDENTITY(1,1) PRIMARY KEY,
    gate_item_row_id INT,
    gate_item_name VARCHAR(300),
    competitor_item_id INT,
    competitor_name VARCHAR(200),
    competitor_item_name VARCHAR(300),
    competitor_item_quantity VARCHAR(100),
    competitor_item_brand VARCHAR(200),
    gate_item_description NVARCHAR(4000),
    gate_parent_category VARCHAR(150),
    gate_sales_category VARCHAR(150),
    competitor_item_description NVARCHAR(4000),
    competitor_parent_category VARCHAR(150),
    competitor_sales_category VARCHAR(150),
    competitor_item_price DECIMAL(10,2),     
    competitor_item_currency VARCHAR(10),  
    competitor_catalog_name VARCHAR(500),
    competitor_catalog_start DATE,
    competitor_catalog_end DATE,
    competitor_catalog_page INT, 
    similarity_score FLOAT,
    reasoning VARCHAR(500),
    tags VARCHAR(200),
    created_at DATETIME DEFAULT GETDATE()
);